name: Continuous Integration

on:
  push:
    branches:
      - main  # Виконання CI при пуші в main
  workflow_dispatch:  # Дозволяє запускати вручну через інтерфейс GitHub

jobs:
  ci-job:
    runs-on: ubuntu-latest  # Операційна система

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2  # Клонування репозиторію

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Встановіть версію Python, яку використовуєте

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Для Python проектів, де є файл requirements.txt з переліком залежностей

    - name: Build the project
      run: |
        # Якщо необхідно, вказати команду для побудови проекту. Наприклад:
        python setup.py install

    - name: Run unit tests
      run: |
        pytest  # Запуск юніт-тестів (наприклад, через pytest для Python)

    - name: Commit changes if any updates
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Automated update after CI run" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Verify the script executed
      run: |
        echo "CI completed successfully!"
