name: Continuous Integration

on:
  push:
    branches:
      - main  # Виконання CI при пуші в main
  workflow_dispatch:  # Дозволяє запускати вручну через інтерфейс GitHub

jobs:
  ci-job:
    runs-on: ubuntu-latest  # Операційна система

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2  # Клонування репозиторію

    - name: Set up environment
      run: |
        # Наприклад, для Node.js проекту. Замініть на потрібний пакет.
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Install dependencies
      run: |
        npm install  # Замініть на ваш тип залежностей, для Python - pip install, для Java - mvn install

    - name: Build the project
      run: |
        npm run build  # Замініть на команду для побудови вашого проекту

    - name: Run unit tests
      run: |
        npm test  # Команда для запуску юніт-тестів (для Python - pytest, для Java - mvn test)

    - name: Commit changes if any updates
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Automated update after CI run" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Verify the script executed
      run: |
        echo "CI completed successfully!"
