name: Continuous Integration

on:
  push:
    branches:
      - main  # Запуск CI при push в main
  workflow_dispatch:  # Дозволяє запускати процес вручну через інтерфейс GitHub

jobs:
  ci-job:
    runs-on: ubuntu-latest  # Операційна система, можна змінити на windows-latest або macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Клонування вашого репозиторію

    - name: Set up environment
      run: |
        # Команди для встановлення програмного забезпечення для конкретного проекту
        sudo apt-get update
        sudo apt-get install -y build-essential  # Заміна на пакети для вашої технології (наприклад, Python або Node.js)

    - name: Install dependencies
      run: |
        # Якщо це Node.js проект, наприклад
        npm install  # Замініть на потрібний менеджер пакетів, наприклад pip install для Python

    - name: Build the project
      run: |
        # Замініть команду на ту, що підходить для вашої технології (для Node.js це може бути `npm run build`)
        npm run build  # Примітка: замінити команду для іншого середовища (наприклад, Python, Java)

    - name: Run unit tests
      run: |
        # Команди для запуску юніт-тестів
        npm test  # Замість цього використовувати команду тестування відповідно до вашої технології

    - name: Commit changes if any updates
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Automated update after CI run" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Verify the script executed
      run: |
        echo "CI completed successfully!"
